CREATE TABLE sessions (
    session_id TEXT PRIMARY KEY,
    protocol_version INTEGER NOT NULL DEFAULT 2,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    timezone TEXT NOT NULL,
    device_label TEXT NOT NULL,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    wall_elapsed_ms INTEGER NOT NULL DEFAULT 0,
    manual_pause_ms INTEGER NOT NULL DEFAULT 0,
    auto_silence_skipped_ms INTEGER NOT NULL DEFAULT 0,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    capture_state TEXT NOT NULL,
    capture_activity TEXT NOT NULL DEFAULT 'idle',
    capture_policy TEXT NOT NULL DEFAULT 'voice_activity_auto_pause_v1',
    vad_engine TEXT,
    remote_state TEXT NOT NULL DEFAULT 'local_only',
    server_initialized INTEGER NOT NULL DEFAULT 0,
    complete_sent INTEGER NOT NULL DEFAULT 0,
    poll_count INTEGER NOT NULL DEFAULT 0,
    chunks_uploaded INTEGER NOT NULL DEFAULT 0,
    chunks_transcribed INTEGER NOT NULL DEFAULT 0,
    github_url TEXT,
    github_commit_sha TEXT,
    last_error TEXT,
    retry_at_epoch_ms INTEGER,
    manual_pause_started_epoch_ms INTEGER,
    audio_deleted INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL
);
CREATE TABLE chunks (
    session_id TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    start_ms INTEGER NOT NULL,
    end_ms INTEGER NOT NULL,
    wall_start_ms INTEGER NOT NULL DEFAULT 0,
    wall_end_ms INTEGER NOT NULL DEFAULT 0,
    path TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    mime_type TEXT NOT NULL DEFAULT 'audio/mp4',
    uploaded INTEGER NOT NULL DEFAULT 0,
    transcript_json TEXT,
    PRIMARY KEY (session_id, chunk_index),
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);
PRAGMA user_version=3;
